import { createServerFn } from "@tanstack/react-start";
import { z } from "zod";

// ---------- Fully Gemini-powered. -----------------------------------------
// Slide content is now generated by Google's Gemini API (free-tier / AI
// Studio key, brought by the user — nothing is stored server-side). The
// request shape and the SlideDeck/SlideSpec types are unchanged, so the
// UI and the .pptx export don't need to know how the deck was produced.

const MAX_PASTE_CHARS = 12000;

// Highly resilient Flash model variations to guarantee execution even during regional routing updates
const GEMINI_MODELS = [
  "gemini-1.5-flash",
  "gemini-1.5-flash-latest",
  "gemini-2.5-flash",
  "gemini-1.5-flash-8b",
];

// ---------- Input validation ----------

const GenerateInput = z.object({
  mode: z.enum(["brief", "paste"]).default("brief"),
  apiKey: z.string().optional().default(""),
  topic: z.string().optional().default(""),
  pastedContent: z
    .string()
    .optional()
    .default("")
    .refine((v) => v.length <= MAX_PASTE_CHARS, {
      message: `Pasted content is too long (max ${MAX_PASTE_CHARS} characters). Please shorten it and try again.`,
    }),
  courseName: z.string().optional().default(""),
  courseCode: z.string().optional().default(""),
  courseLevel: z.string().optional().default(""),
  creditUnits: z.string().optional().default(""),
  contactTime: z.string().optional().default(""),
  slideCount: z.number().int().min(4).max(24).default(10),
  extraNotes: z.string().optional().default(""),
});

type GenerateInputT = z.infer<typeof GenerateInput>;

export type SlideSpec = {
  type: "title" | "identification" | "content" | "list" | "takeaway";
  title: string;
  subtitle?: string;
  body?: string;
  bullets?: string[];
  sections?: { heading: string; description: string }[];
};

export type SlideDeck = {
  courseName: string;
  courseCode: string;
  courseLevel: string;
  creditUnits: string;
  contactTime: string;
  topic: string;
  slides: SlideSpec[];
};

// ---------- Content clamping (protects layout) ----------

const MAX_BULLETS = 6;
const MAX_BULLET_CHARS = 100;
const MAX_BODY_CHARS = 320;
const MAX_TITLE_CHARS = 70;

function clamp(text: string, max: number): string {
  const t = (text ?? "").toString().trim();
  if (t.length <= max) return t;
  return t.slice(0, max - 1).trimEnd() + "…";
}

const SLIDE_TYPES = new Set([
  "title",
  "identification",
  "content",
  "list",
  "takeaway",
]);

function clampSlide(spec: Record<string, unknown>): SlideSpec {
  const type = SLIDE_TYPES.has(spec.type as string)
    ? (spec.type as SlideSpec["type"])
    : "content";

  const bulletsIn = Array.isArray(spec.bullets) ? spec.bullets : [];
  const sectionsIn = Array.isArray(spec.sections) ? spec.sections : [];

  const bullets = bulletsIn
    .filter((b: unknown): b is string => typeof b === "string" && b.trim().length > 0)
    .slice(0, MAX_BULLETS)
    .map((b) => clamp(b, MAX_BULLET_CHARS));

  const sections = sectionsIn
    .filter((s: unknown): s is Record<string, unknown> => !!s && typeof s === "object")
    .filter(
      (s) => typeof s.heading === "string" || typeof s.description === "string",
    )
    .slice(0, 4)
    .map((s) => ({
      heading: clamp(typeof s.heading === "string" ? s.heading : "", 45),
      description: clamp(
        typeof s.description === "string" ? s.description : "",
        150,
      ),
    }));

  return {
    type,
    title: clamp(typeof spec.title === "string" ? spec.title : "", MAX_TITLE_CHARS),
    subtitle:
      typeof spec.subtitle === "string" && spec.subtitle.trim()
        ? clamp(spec.subtitle, 100)
        : undefined,
    body:
      typeof spec.body === "string" && spec.body.trim()
        ? clamp(spec.body, MAX_BODY_CHARS)
        : undefined,
    bullets: bullets.length ? bullets : undefined,
    sections: sections.length ? sections : undefined,
  };
}

// ---------- Gemini structured output schema ----------
// Matches OpenAPI 3.0 schema standard expected by the v1beta API endpoint

const responseSchema = {
  type: "OBJECT",
  properties: {
    courseName: { type: "STRING" },
    courseCode: { type: "STRING" },
    courseLevel: { type: "STRING" },
    creditUnits: { type: "STRING" },
    contactTime: { type: "STRING" },
    topic: { type: "STRING" },
    slides: {
      type: "ARRAY",
      items: {
        type: "OBJECT",
        properties: {
          type: {
            type: "STRING",
            enum: ["title", "identification", "content", "list", "takeaway"],
          },
          title: { type: "STRING" },
          subtitle: { type: "STRING" },
          body: { type: "STRING" },
          bullets: { type: "ARRAY", items: { type: "STRING" } },
          sections: {
            type: "ARRAY",
            items: {
              type: "OBJECT",
              properties: {
                heading: { type: "STRING" },
                description: { type: "STRING" },
              },
              required: ["heading", "description"],
            },
          },
        },
        required: ["type", "title"],
      },
    },
  },
  required: ["topic", "slides"],
};

// ---------- Prompt building ----------

function buildPrompt(data: GenerateInputT): string {
  const identLines = [
    data.courseName && `Course name: ${data.courseName}`,
    data.courseCode && `Course code: ${data.courseCode}`,
    data.courseLevel && `Course level: ${data.courseLevel}`,
    data.creditUnits && `Credit units: ${data.creditUnits}`,
    data.contactTime && `Contact time: ${data.contactTime}`,
  ]
    .filter(Boolean)
    .join("\n");

  const shared = `You are building a university lecture slide deck for Metropolitan
International University (MIU). Return ONLY the deck as structured JSON
matching the provided schema — no commentary, no markdown fences.

Rules:
- Produce exactly ${data.slideCount} slides in the "slides" array, in
  presentation order.
- Slide 1 must be type "title" with the lecture topic as its title.
- Slide 2 must be type "identification" with title "Course Identification
  Details" (the course metadata fields on the deck itself carry the actual
  details — this slide is just a section marker).
- The last slide must be type "takeaway" with 4-6 concise bullet points
  summarizing the key things a student should remember.
- All slides in between should be type "content" or "list", each covering
  one coherent chunk of the material with a clear, specific title.
- Keep titles under ${MAX_TITLE_CHARS} characters, body text under
  ${MAX_BODY_CHARS} characters, and each bullet under ${MAX_BULLET_CHARS}
  characters. Use at most ${MAX_BULLETS} bullets per slide.
- Write clearly and accurately for the stated course level. Do not
  fabricate citations, statistics, or sources.`;

  if (data.mode === "paste") {
    return `${shared}

Base the deck strictly on the source material below — organize, summarize
and structure it, but do not introduce facts that aren't supported by it.
If the source material contains labeled fields like "Course Code:" or
"Credit Units:", use them to fill in courseName/courseCode/courseLevel/
creditUnits/contactTime in the JSON output (and don't repeat those labels
as slide content).

${identLines ? `Known course details (use these unless the source text overrides them):\n${identLines}\n` : ""}
${data.extraNotes ? `Additional guidance from the instructor: ${data.extraNotes}\n` : ""}
Source material:
"""
${data.pastedContent}
"""`;
  }

  return `${shared}

Topic / lecture prompt: ${data.topic}
${identLines ? `\nCourse details:\n${identLines}` : ""}
${data.extraNotes ? `\nAdditional guidance from the instructor: ${data.extraNotes}` : ""}

No source material was provided — use your own subject-matter knowledge to
write accurate, well-organized lecture content on this topic.`;
}

// ---------- Gemini call ----------

class GeminiError extends Error {}

const REQUEST_TIMEOUT_MS = 20_000; 
const RETRYABLE_STATUS = new Set([408, 429, 500, 502, 503, 504]);

function sleep(ms: number) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

async function fetchGeminiOnce(
  apiKey: string,
  prompt: string,
  modelName: string,
): Promise<Record<string, unknown>> {
  const url = `https://generativelanguage.googleapis.com/v1beta/models/${modelName}:generateContent?key=${encodeURIComponent(apiKey)}`;

  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), REQUEST_TIMEOUT_MS);

  let res: Response;
  try {
    res = await fetch(url, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      signal: controller.signal,
      body: JSON.stringify({
        contents: [{ role: "user", parts: [{ text: prompt }] }],
        generationConfig: {
          temperature: 0.6,
          responseMimeType: "application/json",
          responseSchema,
        },
      }),
    });
  } catch (err) {
    if (err instanceof Error && err.name === "AbortError") {
      throw new GeminiError(
        "Gemini took too long to respond. Please try again.",
      );
    }
    throw new GeminiError(
      "Couldn't reach Gemini's API. Check your network connection and try again.",
    );
  } finally {
    clearTimeout(timer);
  }

  if (!res.ok) {
    let errorDetail = "";
    try {
      const errorJson = await res.json();
      errorDetail = errorJson?.error?.message || JSON.stringify(errorJson);
    } catch {
      errorDetail = await res.text().catch(() => "");
    }

    if (res.status === 404) {
      throw new GeminiError(
        `MODEL_NOT_FOUND: Model "${modelName}" is unavailable in your region or layout setup.`,
      );
    }

    if (res.status === 429) {
      const limitErr = new GeminiError(
        "Gemini's rate limit was hit. Wait a moment and try again.",
      );
      (limitErr as GeminiError & { status?: number }).status = 429;
      throw limitErr;
    }

    if (res.status === 400 || res.status === 403) {
      throw new GeminiError(
        `Gemini rejected the request (${res.status}). Gateway Reason: ${errorDetail || "Invalid key configuration or Generative Language API is disabled."}`,
      );
    }
    
    const err = new GeminiError(
      `Gemini request failed (${res.status}). ${errorDetail.slice(0, 200)}`,
    );
    (err as GeminiError & { status?: number }).status = res.status;
    throw err;
  }

  let json: unknown;
  try {
    json = await res.json();
  } catch {
    throw new GeminiError(
      "Gemini returned a response that couldn't be read. Try again.",
    );
  }

  const j = json as Record<string, any> | null | undefined;

  const blockReason = j?.promptFeedback?.blockReason;
  if (blockReason) {
    throw new GeminiError(
      `Gemini declined to generate this deck (${blockReason}). Try adjusting the topic or notes.`,
    );
  }

  const parts = j?.candidates?.[0]?.content?.parts;
  const text: string = Array.isArray(parts)
    ? parts.map((p: { text?: string }) => p?.text ?? "").join("")
    : "";

  if (!text.trim()) {
    const finishReason = j?.candidates?.[0]?.finishReason;
    throw new GeminiError(
      finishReason
        ? `Gemini stopped early (${finishReason}) and returned no content. Try again.`
        : "Gemini returned an empty response. Try again.",
    );
  }

  try {
    const parsed = JSON.parse(text);
    if (!parsed || typeof parsed !== "object" || Array.isArray(parsed)) {
      throw new Error("not an object");
    }
    return parsed as Record<string, unknown>;
  } catch {
    throw new GeminiError(
      "Gemini returned a response that couldn't be parsed. Try again.",
    );
  }
}

async function callGemini(
  apiKey: string,
  prompt: string,
): Promise<Record<string, unknown>> {
  let lastError: unknown;
  let allModelsUnavailable = true;

  // Sequentially try our resilient fallback list
  for (const model of GEMINI_MODELS) {
    const modelMaxAttempts = 2; // Only 2 attempts per model to stay well clear of the gateway rate limit

    for (let attempt = 1; attempt <= modelMaxAttempts; attempt++) {
      try {
        return await fetchGeminiOnce(apiKey, prompt, model);
      } catch (err) {
        lastError = err;
        const status = (err as GeminiError & { status?: number })?.status;

        if (err instanceof GeminiError && err.message.startsWith("MODEL_NOT_FOUND")) {
          break; // Hop to next model in list immediately
        }

        allModelsUnavailable = false;

        // If rate limited, apply a firm cooldown pause and let the queue clear
        if (status === 429) {
          if (attempt === modelMaxAttempts) {
            // Immediately back off on 429 to avoid cascade-failing other models
            throw new GeminiError(
              "Your Gemini API key has hit Google's active rate limit. Please wait 15-30 seconds, ensure you are not double-clicking, and try again."
            );
          }

          // Strict backoff delay to allow the server key bucket to refill
          const backoffDelay = 4000 * attempt; 
          await sleep(backoffDelay);
          continue; 
        }

        const isTimeoutOrNetwork =
          err instanceof GeminiError &&
          /took too long|couldn't reach/i.test(err.message);
        const retryable =
          (status !== undefined && RETRYABLE_STATUS.has(status)) ||
          isTimeoutOrNetwork;
        
        if (!retryable || attempt === modelMaxAttempts) break;
        await sleep(1500 * attempt);
      }
    }
  }
  
  if (lastError instanceof Error) {
    if (allModelsUnavailable && lastError.message.startsWith("MODEL_NOT_FOUND")) {
      throw new GeminiError(
        "All attempted Gemini models (including Flash variants) returned 404 Not Found. This typically indicates your API key is restricted, the Generative Language API is disabled in your project, or your current region/IP address is geoblocked by Google. Please check your regional availability or verify your key configuration in Google AI Studio."
      );
    }
    throw lastError;
  }
  throw new GeminiError("Gemini generation failed on all attempts. Please verify your keys and network.");
}

const MAX_SLIDES_SAFETY_CAP = 40;

function toSlideDeck(
  data: GenerateInputT,
  parsed: Record<string, unknown>,
): SlideDeck {
  try {
    const rawSlides = Array.isArray(parsed.slides) ? parsed.slides : [];
    const slides = rawSlides
      .filter((s): s is Record<string, unknown> => !!s && typeof s === "object")
      .slice(0, MAX_SLIDES_SAFETY_CAP)
      .map(clampSlide)
      .filter((s) => s.title || s.body || s.bullets?.length || s.sections?.length);

    if (!slides.length) {
      throw new GeminiError(
        "Gemini didn't return any usable slides. Try again or adjust your input.",
      );
    }
    if (slides[0].type !== "title") slides[0] = { ...slides[0], type: "title" };

    const topic =
      (typeof parsed.topic === "string" && parsed.topic.trim()) ||
      data.topic ||
      "Untitled Lecture";

    return {
      courseName:
        data.courseName ||
        (typeof parsed.courseName === "string" ? parsed.courseName : "") ||
        "",
      courseCode:
        data.courseCode ||
        (typeof parsed.courseCode === "string" ? parsed.courseCode : "") ||
        "",
      courseLevel:
        data.courseLevel ||
        (typeof parsed.courseLevel === "string" ? parsed.courseLevel : "") ||
        "",
      creditUnits:
        data.creditUnits ||
        (typeof parsed.creditUnits === "string" ? parsed.creditUnits : "") ||
        "",
      contactTime:
        data.contactTime ||
        (typeof parsed.contactTime === "string" ? parsed.contactTime : "") ||
        "",
      topic: clamp(topic, MAX_TITLE_CHARS),
      slides,
    };
  } catch (err) {
    if (err instanceof GeminiError) throw err;
    throw new GeminiError(
      "Gemini's response was in an unexpected shape and couldn't be turned into slides. Please try again.",
    );
  }
}

// ---------- Public server function ----------

export const generateDeck = createServerFn({ method: "POST" })
  .inputValidator((data: unknown) => GenerateInput.parse(data))
  .handler(async ({ data }) => {
    if (!data.apiKey.trim()) {
      throw new Error(
        "Add your free Gemini API key first. Get one at https://aistudio.google.com/apikey",
      );
    }
    if (data.mode === "paste" && data.pastedContent.trim().length < 20) {
      throw new Error("Please paste some course material first.");
    }
    if (data.mode === "brief" && !data.topic.trim()) {
      throw new Error("Please enter a topic.");
    }

    try {
      const prompt = buildPrompt(data);
      const parsed = await callGemini(data.apiKey.trim(), prompt);
      return toSlideDeck(data, parsed);
    } catch (err) {
      if (err instanceof Error && err.message) throw new Error(err.message);
      throw new Error(
        "Something went wrong generating the deck. Please try again.",
      );
    }
  });
