/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SlidesRouteImport } from './routes/slides'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as CurriculumRouteImport } from './routes/curriculum'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LectureNotesDeckIdRouteImport } from './routes/lecture-notes.$deckId'
import { Route as CurriculumCurriculumIdRouteImport } from './routes/curriculum.$curriculumId'

const SlidesRoute = SlidesRouteImport.update({
  id: '/slides',
  path: '/slides',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const CurriculumRoute = CurriculumRouteImport.update({
  id: '/curriculum',
  path: '/curriculum',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LectureNotesDeckIdRoute = LectureNotesDeckIdRouteImport.update({
  id: '/lecture-notes/$deckId',
  path: '/lecture-notes/$deckId',
  getParentRoute: () => rootRouteImport,
} as any)
const CurriculumCurriculumIdRoute = CurriculumCurriculumIdRouteImport.update({
  id: '/$curriculumId',
  path: '/$curriculumId',
  getParentRoute: () => CurriculumRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/curriculum': typeof CurriculumRouteWithChildren
  '/notes': typeof NotesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/slides': typeof SlidesRoute
  '/curriculum/$curriculumId': typeof CurriculumCurriculumIdRoute
  '/lecture-notes/$deckId': typeof LectureNotesDeckIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/curriculum': typeof CurriculumRouteWithChildren
  '/notes': typeof NotesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/slides': typeof SlidesRoute
  '/curriculum/$curriculumId': typeof CurriculumCurriculumIdRoute
  '/lecture-notes/$deckId': typeof LectureNotesDeckIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/curriculum': typeof CurriculumRouteWithChildren
  '/notes': typeof NotesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/slides': typeof SlidesRoute
  '/curriculum/$curriculumId': typeof CurriculumCurriculumIdRoute
  '/lecture-notes/$deckId': typeof LectureNotesDeckIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/curriculum'
    | '/notes'
    | '/reset-password'
    | '/slides'
    | '/curriculum/$curriculumId'
    | '/lecture-notes/$deckId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/curriculum'
    | '/notes'
    | '/reset-password'
    | '/slides'
    | '/curriculum/$curriculumId'
    | '/lecture-notes/$deckId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/curriculum'
    | '/notes'
    | '/reset-password'
    | '/slides'
    | '/curriculum/$curriculumId'
    | '/lecture-notes/$deckId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CurriculumRoute: typeof CurriculumRouteWithChildren
  NotesRoute: typeof NotesRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SlidesRoute: typeof SlidesRoute
  LectureNotesDeckIdRoute: typeof LectureNotesDeckIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/slides': {
      id: '/slides'
      path: '/slides'
      fullPath: '/slides'
      preLoaderRoute: typeof SlidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/curriculum': {
      id: '/curriculum'
      path: '/curriculum'
      fullPath: '/curriculum'
      preLoaderRoute: typeof CurriculumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lecture-notes/$deckId': {
      id: '/lecture-notes/$deckId'
      path: '/lecture-notes/$deckId'
      fullPath: '/lecture-notes/$deckId'
      preLoaderRoute: typeof LectureNotesDeckIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/curriculum/$curriculumId': {
      id: '/curriculum/$curriculumId'
      path: '/$curriculumId'
      fullPath: '/curriculum/$curriculumId'
      preLoaderRoute: typeof CurriculumCurriculumIdRouteImport
      parentRoute: typeof CurriculumRoute
    }
  }
}

interface CurriculumRouteChildren {
  CurriculumCurriculumIdRoute: typeof CurriculumCurriculumIdRoute
}

const CurriculumRouteChildren: CurriculumRouteChildren = {
  CurriculumCurriculumIdRoute: CurriculumCurriculumIdRoute,
}

const CurriculumRouteWithChildren = CurriculumRoute._addFileChildren(
  CurriculumRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CurriculumRoute: CurriculumRouteWithChildren,
  NotesRoute: NotesRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SlidesRoute: SlidesRoute,
  LectureNotesDeckIdRoute: LectureNotesDeckIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
