/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SlidesRouteImport } from './routes/slides'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as DataProtectionRouteImport } from './routes/data-protection'
import { Route as CurriculumRouteImport } from './routes/curriculum'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccessibilityRouteImport } from './routes/accessibility'
import { Route as AcademicPolicyRouteImport } from './routes/academic-policy'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SharedTokenRouteImport } from './routes/shared.$token'
import { Route as QuizDeckIdRouteImport } from './routes/quiz.$deckId'
import { Route as LectureNotesDeckIdRouteImport } from './routes/lecture-notes.$deckId'
import { Route as CurriculumCurriculumIdRouteImport } from './routes/curriculum.$curriculumId'
import { Route as ApiQuizStreamRouteImport } from './routes/api.quiz-stream'
import { Route as ApiLectureNotesStreamRouteImport } from './routes/api.lecture-notes-stream'
import { Route as ApiCurriculumNotesStreamRouteImport } from './routes/api.curriculum-notes-stream'
import { Route as QuizTakeQuizIdRouteImport } from './routes/quiz.take.$quizId'
import { Route as NotesReadNotesIdRouteImport } from './routes/notes.read.$notesId'
import { Route as CurriculumCurriculumIdStructureRouteImport } from './routes/curriculum.$curriculumId.structure'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SlidesRoute = SlidesRouteImport.update({
  id: '/slides',
  path: '/slides',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const DataProtectionRoute = DataProtectionRouteImport.update({
  id: '/data-protection',
  path: '/data-protection',
  getParentRoute: () => rootRouteImport,
} as any)
const CurriculumRoute = CurriculumRouteImport.update({
  id: '/curriculum',
  path: '/curriculum',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessibilityRoute = AccessibilityRouteImport.update({
  id: '/accessibility',
  path: '/accessibility',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicPolicyRoute = AcademicPolicyRouteImport.update({
  id: '/academic-policy',
  path: '/academic-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SharedTokenRoute = SharedTokenRouteImport.update({
  id: '/shared/$token',
  path: '/shared/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizDeckIdRoute = QuizDeckIdRouteImport.update({
  id: '/$deckId',
  path: '/$deckId',
  getParentRoute: () => QuizRoute,
} as any)
const LectureNotesDeckIdRoute = LectureNotesDeckIdRouteImport.update({
  id: '/lecture-notes/$deckId',
  path: '/lecture-notes/$deckId',
  getParentRoute: () => rootRouteImport,
} as any)
const CurriculumCurriculumIdRoute = CurriculumCurriculumIdRouteImport.update({
  id: '/$curriculumId',
  path: '/$curriculumId',
  getParentRoute: () => CurriculumRoute,
} as any)
const ApiQuizStreamRoute = ApiQuizStreamRouteImport.update({
  id: '/api/quiz-stream',
  path: '/api/quiz-stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLectureNotesStreamRoute = ApiLectureNotesStreamRouteImport.update({
  id: '/api/lecture-notes-stream',
  path: '/api/lecture-notes-stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCurriculumNotesStreamRoute =
  ApiCurriculumNotesStreamRouteImport.update({
    id: '/api/curriculum-notes-stream',
    path: '/api/curriculum-notes-stream',
    getParentRoute: () => rootRouteImport,
  } as any)
const QuizTakeQuizIdRoute = QuizTakeQuizIdRouteImport.update({
  id: '/take/$quizId',
  path: '/take/$quizId',
  getParentRoute: () => QuizRoute,
} as any)
const NotesReadNotesIdRoute = NotesReadNotesIdRouteImport.update({
  id: '/read/$notesId',
  path: '/read/$notesId',
  getParentRoute: () => NotesRoute,
} as any)
const CurriculumCurriculumIdStructureRoute =
  CurriculumCurriculumIdStructureRouteImport.update({
    id: '/structure',
    path: '/structure',
    getParentRoute: () => CurriculumCurriculumIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/academic-policy': typeof AcademicPolicyRoute
  '/accessibility': typeof AccessibilityRoute
  '/admin': typeof AdminRoute
  '/curriculum': typeof CurriculumRouteWithChildren
  '/data-protection': typeof DataProtectionRoute
  '/notes': typeof NotesRouteWithChildren
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/quiz': typeof QuizRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/slides': typeof SlidesRoute
  '/terms': typeof TermsRoute
  '/api/curriculum-notes-stream': typeof ApiCurriculumNotesStreamRoute
  '/api/lecture-notes-stream': typeof ApiLectureNotesStreamRoute
  '/api/quiz-stream': typeof ApiQuizStreamRoute
  '/curriculum/$curriculumId': typeof CurriculumCurriculumIdRouteWithChildren
  '/lecture-notes/$deckId': typeof LectureNotesDeckIdRoute
  '/quiz/$deckId': typeof QuizDeckIdRoute
  '/shared/$token': typeof SharedTokenRoute
  '/curriculum/$curriculumId/structure': typeof CurriculumCurriculumIdStructureRoute
  '/notes/read/$notesId': typeof NotesReadNotesIdRoute
  '/quiz/take/$quizId': typeof QuizTakeQuizIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/academic-policy': typeof AcademicPolicyRoute
  '/accessibility': typeof AccessibilityRoute
  '/admin': typeof AdminRoute
  '/curriculum': typeof CurriculumRouteWithChildren
  '/data-protection': typeof DataProtectionRoute
  '/notes': typeof NotesRouteWithChildren
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/quiz': typeof QuizRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/slides': typeof SlidesRoute
  '/terms': typeof TermsRoute
  '/api/curriculum-notes-stream': typeof ApiCurriculumNotesStreamRoute
  '/api/lecture-notes-stream': typeof ApiLectureNotesStreamRoute
  '/api/quiz-stream': typeof ApiQuizStreamRoute
  '/curriculum/$curriculumId': typeof CurriculumCurriculumIdRouteWithChildren
  '/lecture-notes/$deckId': typeof LectureNotesDeckIdRoute
  '/quiz/$deckId': typeof QuizDeckIdRoute
  '/shared/$token': typeof SharedTokenRoute
  '/curriculum/$curriculumId/structure': typeof CurriculumCurriculumIdStructureRoute
  '/notes/read/$notesId': typeof NotesReadNotesIdRoute
  '/quiz/take/$quizId': typeof QuizTakeQuizIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/academic-policy': typeof AcademicPolicyRoute
  '/accessibility': typeof AccessibilityRoute
  '/admin': typeof AdminRoute
  '/curriculum': typeof CurriculumRouteWithChildren
  '/data-protection': typeof DataProtectionRoute
  '/notes': typeof NotesRouteWithChildren
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/quiz': typeof QuizRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/slides': typeof SlidesRoute
  '/terms': typeof TermsRoute
  '/api/curriculum-notes-stream': typeof ApiCurriculumNotesStreamRoute
  '/api/lecture-notes-stream': typeof ApiLectureNotesStreamRoute
  '/api/quiz-stream': typeof ApiQuizStreamRoute
  '/curriculum/$curriculumId': typeof CurriculumCurriculumIdRouteWithChildren
  '/lecture-notes/$deckId': typeof LectureNotesDeckIdRoute
  '/quiz/$deckId': typeof QuizDeckIdRoute
  '/shared/$token': typeof SharedTokenRoute
  '/curriculum/$curriculumId/structure': typeof CurriculumCurriculumIdStructureRoute
  '/notes/read/$notesId': typeof NotesReadNotesIdRoute
  '/quiz/take/$quizId': typeof QuizTakeQuizIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/academic-policy'
    | '/accessibility'
    | '/admin'
    | '/curriculum'
    | '/data-protection'
    | '/notes'
    | '/privacy-policy'
    | '/quiz'
    | '/reset-password'
    | '/settings'
    | '/slides'
    | '/terms'
    | '/api/curriculum-notes-stream'
    | '/api/lecture-notes-stream'
    | '/api/quiz-stream'
    | '/curriculum/$curriculumId'
    | '/lecture-notes/$deckId'
    | '/quiz/$deckId'
    | '/shared/$token'
    | '/curriculum/$curriculumId/structure'
    | '/notes/read/$notesId'
    | '/quiz/take/$quizId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/academic-policy'
    | '/accessibility'
    | '/admin'
    | '/curriculum'
    | '/data-protection'
    | '/notes'
    | '/privacy-policy'
    | '/quiz'
    | '/reset-password'
    | '/settings'
    | '/slides'
    | '/terms'
    | '/api/curriculum-notes-stream'
    | '/api/lecture-notes-stream'
    | '/api/quiz-stream'
    | '/curriculum/$curriculumId'
    | '/lecture-notes/$deckId'
    | '/quiz/$deckId'
    | '/shared/$token'
    | '/curriculum/$curriculumId/structure'
    | '/notes/read/$notesId'
    | '/quiz/take/$quizId'
  id:
    | '__root__'
    | '/'
    | '/academic-policy'
    | '/accessibility'
    | '/admin'
    | '/curriculum'
    | '/data-protection'
    | '/notes'
    | '/privacy-policy'
    | '/quiz'
    | '/reset-password'
    | '/settings'
    | '/slides'
    | '/terms'
    | '/api/curriculum-notes-stream'
    | '/api/lecture-notes-stream'
    | '/api/quiz-stream'
    | '/curriculum/$curriculumId'
    | '/lecture-notes/$deckId'
    | '/quiz/$deckId'
    | '/shared/$token'
    | '/curriculum/$curriculumId/structure'
    | '/notes/read/$notesId'
    | '/quiz/take/$quizId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcademicPolicyRoute: typeof AcademicPolicyRoute
  AccessibilityRoute: typeof AccessibilityRoute
  AdminRoute: typeof AdminRoute
  CurriculumRoute: typeof CurriculumRouteWithChildren
  DataProtectionRoute: typeof DataProtectionRoute
  NotesRoute: typeof NotesRouteWithChildren
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  QuizRoute: typeof QuizRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  SettingsRoute: typeof SettingsRoute
  SlidesRoute: typeof SlidesRoute
  TermsRoute: typeof TermsRoute
  ApiCurriculumNotesStreamRoute: typeof ApiCurriculumNotesStreamRoute
  ApiLectureNotesStreamRoute: typeof ApiLectureNotesStreamRoute
  ApiQuizStreamRoute: typeof ApiQuizStreamRoute
  LectureNotesDeckIdRoute: typeof LectureNotesDeckIdRoute
  SharedTokenRoute: typeof SharedTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/slides': {
      id: '/slides'
      path: '/slides'
      fullPath: '/slides'
      preLoaderRoute: typeof SlidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-protection': {
      id: '/data-protection'
      path: '/data-protection'
      fullPath: '/data-protection'
      preLoaderRoute: typeof DataProtectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/curriculum': {
      id: '/curriculum'
      path: '/curriculum'
      fullPath: '/curriculum'
      preLoaderRoute: typeof CurriculumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessibility': {
      id: '/accessibility'
      path: '/accessibility'
      fullPath: '/accessibility'
      preLoaderRoute: typeof AccessibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academic-policy': {
      id: '/academic-policy'
      path: '/academic-policy'
      fullPath: '/academic-policy'
      preLoaderRoute: typeof AcademicPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shared/$token': {
      id: '/shared/$token'
      path: '/shared/$token'
      fullPath: '/shared/$token'
      preLoaderRoute: typeof SharedTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/$deckId': {
      id: '/quiz/$deckId'
      path: '/$deckId'
      fullPath: '/quiz/$deckId'
      preLoaderRoute: typeof QuizDeckIdRouteImport
      parentRoute: typeof QuizRoute
    }
    '/lecture-notes/$deckId': {
      id: '/lecture-notes/$deckId'
      path: '/lecture-notes/$deckId'
      fullPath: '/lecture-notes/$deckId'
      preLoaderRoute: typeof LectureNotesDeckIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/curriculum/$curriculumId': {
      id: '/curriculum/$curriculumId'
      path: '/$curriculumId'
      fullPath: '/curriculum/$curriculumId'
      preLoaderRoute: typeof CurriculumCurriculumIdRouteImport
      parentRoute: typeof CurriculumRoute
    }
    '/api/quiz-stream': {
      id: '/api/quiz-stream'
      path: '/api/quiz-stream'
      fullPath: '/api/quiz-stream'
      preLoaderRoute: typeof ApiQuizStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/lecture-notes-stream': {
      id: '/api/lecture-notes-stream'
      path: '/api/lecture-notes-stream'
      fullPath: '/api/lecture-notes-stream'
      preLoaderRoute: typeof ApiLectureNotesStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/curriculum-notes-stream': {
      id: '/api/curriculum-notes-stream'
      path: '/api/curriculum-notes-stream'
      fullPath: '/api/curriculum-notes-stream'
      preLoaderRoute: typeof ApiCurriculumNotesStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/take/$quizId': {
      id: '/quiz/take/$quizId'
      path: '/take/$quizId'
      fullPath: '/quiz/take/$quizId'
      preLoaderRoute: typeof QuizTakeQuizIdRouteImport
      parentRoute: typeof QuizRoute
    }
    '/notes/read/$notesId': {
      id: '/notes/read/$notesId'
      path: '/read/$notesId'
      fullPath: '/notes/read/$notesId'
      preLoaderRoute: typeof NotesReadNotesIdRouteImport
      parentRoute: typeof NotesRoute
    }
    '/curriculum/$curriculumId/structure': {
      id: '/curriculum/$curriculumId/structure'
      path: '/structure'
      fullPath: '/curriculum/$curriculumId/structure'
      preLoaderRoute: typeof CurriculumCurriculumIdStructureRouteImport
      parentRoute: typeof CurriculumCurriculumIdRoute
    }
  }
}

interface CurriculumCurriculumIdRouteChildren {
  CurriculumCurriculumIdStructureRoute: typeof CurriculumCurriculumIdStructureRoute
}

const CurriculumCurriculumIdRouteChildren: CurriculumCurriculumIdRouteChildren =
  {
    CurriculumCurriculumIdStructureRoute: CurriculumCurriculumIdStructureRoute,
  }

const CurriculumCurriculumIdRouteWithChildren =
  CurriculumCurriculumIdRoute._addFileChildren(
    CurriculumCurriculumIdRouteChildren,
  )

interface CurriculumRouteChildren {
  CurriculumCurriculumIdRoute: typeof CurriculumCurriculumIdRouteWithChildren
}

const CurriculumRouteChildren: CurriculumRouteChildren = {
  CurriculumCurriculumIdRoute: CurriculumCurriculumIdRouteWithChildren,
}

const CurriculumRouteWithChildren = CurriculumRoute._addFileChildren(
  CurriculumRouteChildren,
)

interface NotesRouteChildren {
  NotesReadNotesIdRoute: typeof NotesReadNotesIdRoute
}

const NotesRouteChildren: NotesRouteChildren = {
  NotesReadNotesIdRoute: NotesReadNotesIdRoute,
}

const NotesRouteWithChildren = NotesRoute._addFileChildren(NotesRouteChildren)

interface QuizRouteChildren {
  QuizDeckIdRoute: typeof QuizDeckIdRoute
  QuizTakeQuizIdRoute: typeof QuizTakeQuizIdRoute
}

const QuizRouteChildren: QuizRouteChildren = {
  QuizDeckIdRoute: QuizDeckIdRoute,
  QuizTakeQuizIdRoute: QuizTakeQuizIdRoute,
}

const QuizRouteWithChildren = QuizRoute._addFileChildren(QuizRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcademicPolicyRoute: AcademicPolicyRoute,
  AccessibilityRoute: AccessibilityRoute,
  AdminRoute: AdminRoute,
  CurriculumRoute: CurriculumRouteWithChildren,
  DataProtectionRoute: DataProtectionRoute,
  NotesRoute: NotesRouteWithChildren,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  QuizRoute: QuizRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  SettingsRoute: SettingsRoute,
  SlidesRoute: SlidesRoute,
  TermsRoute: TermsRoute,
  ApiCurriculumNotesStreamRoute: ApiCurriculumNotesStreamRoute,
  ApiLectureNotesStreamRoute: ApiLectureNotesStreamRoute,
  ApiQuizStreamRoute: ApiQuizStreamRoute,
  LectureNotesDeckIdRoute: LectureNotesDeckIdRoute,
  SharedTokenRoute: SharedTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
